create database PERSONLD;
use PERSONLD;
CREATE TABLE Person(PERSONLDS varchar(20),ID integer(10), EMAIL varchar(20), P_NAME varchar(20), AGE integer(10));
-- SELECT * FROM Person;
-- SELECT 1,2,'P'; 
-- SELECT 'HELLO'||'WORLD';
-- SELECT 1 AS col1;
-- SELECT  UPPER(p_NAME), EMAIL FROM Person; 
-- SELECT 'NAMA:' || P_NAME, EMAIL FROM Person;
-- SELECT * FROM Person ORDER BY ID ASC; -- ASC=ASCENDING ORDER OF ID(SMALL TO BIG DESC=(BIG TO SMALL)
-- SELECT * FROM Person WHERE ID < 10; -- WHERE=JUST OUTPUT ID NOT ALL Person TABLES, LIKE JUST WANT GET ONLY WANT SOMETHING
-- SELECT * FROM Person WHERE EMAIL LIKE %gmail%; -- LIKE=EQUALS(), %gmail%= IN THE MIDDLE, %gmail'= IN THE END, 'gmail%= IN THE BEGINNING
-- SELECT * FROM Person WHERE ID > 1 AND AGE >10; -- AND = NEED ALL IF IS TRUE
-- SELECT * FROM Person WHERE ID > 1 OR AGE >10; -- OR = JUST NEED ONE IF IS TRUE IS OK
-- SELECT * FROM Person WHERE AGE BETWEEN 12 AND 15; -- >=12 <=15 :12,13,14,15 IS OK
-- SELECT * FROM Person WHERE ID IS 1; -- ID JUST 1 IS OK
-- SELECT * FROM Person WHERE ID IS NOT 1; -- JUST 1 NOT OK ,OTHER ANY ID ALL OK
/* GROUP BY WITH AGGREGATE FUNCTION
- AVG(), COUNT(), MAX(), MIN(), SUM() --AVG = ALL VALUES / HOW MANY VALUES, COUNT = HOW MANY VALUES
-- SELECT COUNT(*) FROM Person; 
-- SELECT ID, COUNT(*) FROM Person GROUP BY IF*/
-- DROP TABLE Person;
-- SELECT * FROM Person;
-- INSERT INTO Person(PERSONLDS ,ID , EMAIL , P_NAME , AGE )
-- ALUES ('T', 001, 'G', 'TOM', 15);

